[CmdletBinding()]
param(
    [string]$DatabaseUrl,
    [switch]$ConfirmNewDatabase,
    [switch]$Install,
    [switch]$SetupOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = $PSScriptRoot
$backendDir = Join-Path $repoRoot 'backend'
$frontendDir = Join-Path $repoRoot 'frontend'
$backendEnvPath = Join-Path $backendDir '.env'
$frontendEnvPath = Join-Path $frontendDir '.env'
$venvDir = Join-Path $backendDir '.venv-demo'
$venvPython = Join-Path $venvDir 'Scripts\python.exe'

function New-HexSecret {
    $bytes = New-Object byte[] 32
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    }
    finally {
        $generator.Dispose()
    }
    return -join ($bytes | ForEach-Object { $_.ToString('x2') })
}

function ConvertFrom-SecureValue([System.Security.SecureString]$Value) {
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Value)
    try {
        return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
}

function Assert-PostgresUrl([string]$Value) {
    if ($Value -notmatch '^postgres(?:ql)?(?:\+psycopg)?://') {
        throw 'The demo requires a PostgreSQL URL beginning with postgres://, postgresql://, or postgresql+psycopg://.'
    }
    if ($Value -match 'replace-me|PROJECT_REF|ENCODED_PASSWORD|yourpassword') {
        throw 'Replace all placeholder values with credentials for your newly created personal database.'
    }
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [IO.File]::WriteAllText($Path, $Content, $encoding)
}

if (Test-Path -LiteralPath $backendEnvPath) {
    $backendEnv = Get-Content -LiteralPath $backendEnvPath -Raw
    if ($backendEnv -notmatch '(?m)^DEMO_MODE=(true|1)\s*$' -or
        $backendEnv -notmatch '(?m)^DB_FALLBACK_ENABLED=(false|0)\s*$') {
        throw 'backend/.env is not an isolated demo configuration. It was not overwritten. Move it aside and run this script again.'
    }

    $configuredUrl = [regex]::Match($backendEnv, '(?m)^DATABASE_URL=(.+)$').Groups[1].Value.Trim()
    Assert-PostgresUrl $configuredUrl
    if ($DatabaseUrl -and $DatabaseUrl -ne $configuredUrl) {
        throw 'backend/.env already uses a different database. It was not overwritten.'
    }
}
else {
    if (-not $DatabaseUrl) {
        $secureUrl = Read-Host 'Paste the NEW personal PostgreSQL/Supabase connection URL' -AsSecureString
        $DatabaseUrl = ConvertFrom-SecureValue $secureUrl
    }
    Assert-PostgresUrl $DatabaseUrl

    if (-not $ConfirmNewDatabase) {
        $confirmation = Read-Host 'Type NEW to confirm this database is separate from the team database'
        if ($confirmation -cne 'NEW') {
            throw 'Database confirmation failed. No environment file was created.'
        }
    }

    $secret = New-HexSecret
    $backendEnv = @"
# Generated by run-demo.ps1. This file is ignored by Git.
DEMO_MODE=true
FLASK_DEBUG=1
FLASK_RUN_HOST=127.0.0.1
FLASK_RUN_PORT=5001
SECRET_KEY=$secret
DATABASE_URL=$DatabaseUrl
DB_AUTO_CREATE=1
SEED_DEMO_DATA=1
RULES_SEED_VERSION=v3
REQUIRE_POSTGRES=1
DB_FALLBACK_ENABLED=0
DB_FALLBACK_AUTO_CREATE=0
DB_FALLBACK_SEED=0
CORS_ORIGINS=http://127.0.0.1:5173,http://localhost:5173
"@
    Write-Utf8NoBom $backendEnvPath $backendEnv
    Write-Host 'Created backend/.env with a generated secret and the new PostgreSQL database.' -ForegroundColor Green
}

if (Test-Path -LiteralPath $frontendEnvPath) {
    $frontendEnv = Get-Content -LiteralPath $frontendEnvPath -Raw
    if ($frontendEnv -notmatch '(?m)^VITE_DEMO_MODE=(true|1)\s*$' -or
        $frontendEnv -notmatch '(?m)^VITE_API_BASE_URL=http://127\.0\.0\.1:5001/api\s*$') {
        throw 'frontend/.env is not the local independent demo configuration. It was not overwritten.'
    }
}
else {
    $frontendEnv = @"
# Generated by run-demo.ps1. This file is ignored by Git.
VITE_API_BASE_URL=http://127.0.0.1:5001/api
VITE_API_TIMEOUT_MS=20000
VITE_DEMO_MODE=true
VITE_DEMO_LABEL=Independent Demo
"@
    Write-Utf8NoBom $frontendEnvPath $frontendEnv
    Write-Host 'Created frontend/.env for the local independent demo.' -ForegroundColor Green
}

if ($SetupOnly) {
    Write-Host 'Demo environment setup is complete. No services were started.' -ForegroundColor Cyan
    exit 0
}

$createdVenv = $false
if (-not (Test-Path -LiteralPath $venvPython)) {
    $python = Get-Command python -ErrorAction SilentlyContinue
    if (-not $python) {
        throw 'Python 3.11 or newer is required.'
    }
    $versionSupported = & $python.Source -c "import sys; print(int(sys.version_info >= (3, 11)))"
    if ($LASTEXITCODE -ne 0 -or $versionSupported.Trim() -ne '1') {
        throw 'Python 3.11 or newer is required.'
    }
    & $python.Source -m venv $venvDir
    if (-not (Test-Path -LiteralPath $venvPython)) {
        throw 'Unable to create backend/.venv-demo.'
    }
    $createdVenv = $true
}

if ($createdVenv -or $Install) {
    & $venvPython -m pip install -r (Join-Path $backendDir 'requirements.txt')
    if ($LASTEXITCODE -ne 0) { throw 'Backend dependency installation failed.' }
}

$npm = Get-Command npm.cmd -ErrorAction SilentlyContinue
if (-not $npm) { throw 'Node.js and npm are required.' }
if ($Install -or -not (Test-Path -LiteralPath (Join-Path $frontendDir 'node_modules'))) {
    & $npm.Source install --prefix $frontendDir
    if ($LASTEXITCODE -ne 0) { throw 'Frontend dependency installation failed.' }
}

$escapedBackend = $backendDir.Replace("'", "''")
$escapedFrontend = $frontendDir.Replace("'", "''")
$escapedPython = $venvPython.Replace("'", "''")
$escapedNpm = $npm.Source.Replace("'", "''")
$backendCommand = "Set-Location -LiteralPath '$escapedBackend'; & '$escapedPython' run.py"
$frontendCommand = "Set-Location -LiteralPath '$escapedFrontend'; & '$escapedNpm' run dev -- --host 127.0.0.1"

Start-Process powershell.exe -ArgumentList @('-NoExit', '-NoProfile', '-Command', $backendCommand)
Start-Process powershell.exe -ArgumentList @('-NoExit', '-NoProfile', '-Command', $frontendCommand)

Write-Host ''
Write-Host 'Independent demo starting:' -ForegroundColor Cyan
Write-Host '  Frontend: http://127.0.0.1:5173'
Write-Host '  Backend:  http://127.0.0.1:5001'
Write-Host '  Health:   http://127.0.0.1:5001/api/health'
Write-Host 'The first backend start creates and seeds the schema in your new database.'
